// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.2.3.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "ch.qos.logback" % "logback-classic" % "1.1.7",
  "ch.qos.logback" % "logback-core" % "1.1.7",
  "com.chuusai" % "shapeless_2.11" % "2.3.2",
  "com.google.guava" % "guava" % "19.0",
  "io.iohk" % "iodb_2.11" % "1.0-M1-SNAPSHOT",
  "jline" % "jline" % "2.12.1",
  "net.jcip" % "jcip-annotations" % "1.0",
  "net.jpountz.lz4" % "lz4" % "1.3.0",
  "org.consensusresearch" % "scrypto_2.11" % "1.2.0-RC3",
  "org.eclipse.collections" % "eclipse-collections" % "7.1.0",
  "org.eclipse.collections" % "eclipse-collections-api" % "7.1.0",
  "org.eclipse.collections" % "eclipse-collections-forkjoin" % "7.1.0",
  "org.jetbrains.kotlin" % "kotlin-runtime" % "1.0.2",
  "org.jetbrains.kotlin" % "kotlin-stdlib" % "1.0.2",
  "org.mapdb" % "elsa" % "3.0.0-M5",
  "org.mapdb" % "mapdb" % "3.0.1",
  "org.scala-lang.modules" % "scala-parser-combinators_2.11" % "1.0.4",
  "org.scala-lang.modules" % "scala-xml_2.11" % "1.0.4",
  "org.scoverage" % "scalac-scoverage-plugin_2.11" % "1.1.1",
  "org.scoverage" % "scalac-scoverage-runtime_2.11" % "1.1.1",
  "org.slf4j" % "slf4j-api" % "1.7.21",
  "org.typelevel" % "macro-compat_2.11" % "1.1.1",
  "org.whispersystems" % "curve25519-java" % "0.3.0"
)
// LIBRARY_DEPENDENCIES_HASH 31ab47a7cc19e62d80a9d58b76538d8f9dcd37e9
