// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "ch.qos.logback" % "logback-classic" % "1.2.3",
  "ch.qos.logback" % "logback-core" % "1.2.3",
  "com.google.guava" % "guava" % "19.0",
  "net.jpountz.lz4" % "lz4" % "1.3.0",
  "org.bouncycastle" % "bcprov-jdk15on" % "1.58",
  "org.rudogma" % "supertagged_2.12" % "1.3",
  "org.scorexfoundation" % "iodb_2.12" % "0.3.2-SNAPSHOT",
  "org.scorexfoundation" % "scrypto_2.12" % "2.0.3",
  "org.slf4j" % "slf4j-api" % "1.7.25",
  "org.whispersystems" % "curve25519-java" % "0.4.1"
)
// LIBRARY_DEPENDENCIES_HASH 5198a6bf21b48fbeb0a2a3ce5fe24b3f0ceed7ba
